# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - sacr-coref

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python version
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Create and activate virtual environment
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Step 4: Upgrade pip and install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      # Step 5: Zip the contents of the application while excluding unnecessary files
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x ".git/*" -x ".github/*" -x "venv/*" -x "*.pyc" -x "__pycache__/*"

      # Step 6: Upload the zipped artifact for deployment jobs
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      # Step 1: Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Step 2: Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Step 3: Login to Azure using credentials stored in GitHub Secrets
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AECF7CF1C091435DA63A41D438FB6D26 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E4CA07C89964D72B998F9E424CC12D3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3B3DF622723249D3B590FA7CDE7D077C }}

      # Step 4: Deploy the application to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'sacr-coref'  # Ensure this matches your Azure Web App name
          slot-name: 'Production'  # Use the default slot or specify a slot name if needed
        timeout-minutes: 60  # Increase timeout as necessary to avoid timeouts during deployment

      # Optional Step: Show directory structure for debugging purposes
      - name: Show directory structure (for debugging)
        run: ls -R
